### ISSUE TITLE
Token refresh hangs forever

### ISSUE THREAD

**Issue by harti2006** [zalando/tokens#52]
Sometimes, threads hang in this state:

```
pool-8-thread-1" #83 prio=5 os_prio=0 tid=0x00007f3af2195000 nid=0x4537 runnable [0x00007f3ab15ef000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
...
at org.zalando.stups.tokens.AccessTokenRefresher.createToken(AccessTokenRefresher.java:175)
```

We have to verify if timeouts (especially socket timeouts) are being applied correctly.

**Comment by jbellmann** [comment]
@harti2006
What version are you running? Is it the latest release of 'tokens'?

**Comment by harti2006** [comment]
Yes, I think it was tokens `0.9.9` and apache http client `4.3.6`

**Comment by jbellmann** [comment]
thanks for that info, makes it easier to look for possible issues ;-)

**Comment by harti2006** [comment]
@hjacobs suggested to create unit tests that verify if the (default) timeouts are applied correctly. Maybe we can use WireMock for this, or point to a a not reachable url.

**Comment by jbellmann** [comment]
So we configure timeouts for fetching new tokens [here](https://github.com/zalando/tokens/blob/master/src/main/java/org/zalando/stups/tokens/CloseableHttpProvider.java#L66), and we use this config for every request-object [here](https://github.com/zalando/tokens/blob/master/src/main/java/org/zalando/stups/tokens/CloseableHttpProvider.java#L102).

At the first look that seems to be ok, right?

**Comment by hjacobs** [comment]
@jbellmann yes, I also looked briefly at the code and it looks "fine" --- we know for sure that it was hanging in SSL handshake to Plan B Provider (we saw this stacktrace in heap dumps of multiple instances):

```
"pool-52-thread-1" #300 prio=5 os_prio=0 tid=0x00007f139c383800 nid=0x1474 runnable [0x00007f13ec477000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        - locked <0x000000062bee7af0> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        - locked <0x000000062bee7b08> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.zalando.stups.tokens.AccessTokenRefresher.createToken(AccessTokenRefresher.java:210)
```

It might also be a bug in some versions of Apache HTTP Client...

**Comment by jbellmann** [comment]
I opened a new branch and PR for testing timeouts. First implemented test with Wiremock works as expected. Does not hang and throws STE after 2000ms.

**Comment by hjacobs** [comment]
I found something related: https://bugs.openjdk.java.net/browse/JDK-8075484

**Comment by harti2006** [comment]
Oh, and still not fixed.
@jbellmann maybe the timeout needs to be implemented on a higher level (e.g. using your mcb or hystrix)

**Comment by jbellmann** [comment]
@harti2006 but would that free the hanging connections? I'm not sure about that. In what way would I 'close' such hanging connections and clean up resources?

**Comment by hjacobs** [comment]
@jbellmann the resources is the lesser issue, the primary problem is that the Tokens library stops creating new tokens...

**Comment by jbellmann** [comment]
Maybe I have found a way to go with this issue. Please have a look into [this commit](https://github.com/zalando/tokens/pull/53/commits/e785623120f45686e09a40525ad602bb350eba31). If you don't like 'Timer', we can also implement it with 'ScheduledExecutorService'. For an example have a look into [this test](https://github.com/zalando/tokens/blob/e785623120f45686e09a40525ad602bb350eba31/src/test/java/org/zalando/stups/tokens/AbortRequestTest.java).

Let me know what you think.

**Comment by hjacobs** [comment]
@jbellmann I would be fine with "abort" --- **if it works...**, not sure whether "abort" can kill the socket read / thread?

**Comment by jbellmann** [comment]
Lets have a try, I will prepare an release and we will see what happens. It's not so easy to simulate the exact behaviour in a test.

**Comment by jbellmann** [comment]
There is now a version [0.9.9-gh52-1](https://github.com/zalando/tokens/releases/tag/0.9.9-gh52-1) as a replacement for 0.9.9.

**Comment by jbellmann** [comment]
Found [this](https://issues.apache.org/jira/browse/HTTPCLIENT-1478) it's marked as resolved but when you read the comments it seems to be not really fixed in 4.3.4. The last comment mentioned 4.5.1 as the version that works as expected with https.

**Comment by LappleApple** [comment]
Hi @harti2006 @jbellmann @duergner Wondering what the next step here might be ...

**Comment by duergner** [comment]
As discussed on #53 my suggestion would be to mark as `won't fix` and add the information about  http-client >= 4.5.2 to the README.

What do you think @harti2006 / @jbellmann / @hjacobs?

**Comment by jbellmann** [comment]
In the latest [release](https://github.com/zalando/tokens/releases/tag/0.10.0) we add 'httpclient' in latest version (4.5.3) as transitive dependency to avoid this issue.
